##### Intro to Pandas

In [21]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["x","y","z"], index=["a","b","c"])
df.head()

   x  y  z
a  1  2  3
b  4  5  6
c  7  8  9

In [22]:
df.tail(2)

   x  y  z
b  4  5  6
c  7  8  9

In [25]:
df.columns

Index(['x', 'y', 'z'], dtype='object')

In [26]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [51]:
df.index.tolist()

['a', 'b', 'c']

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       3 non-null      int64
 1   y       3 non-null      int64
 2   z       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [31]:
df.describe() # Provide information

         x    y    z
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [33]:
df.nunique()

x    3
y    3
z    3
dtype: int64

In [54]:
df.shape

(3, 3)

##### Loading DataFrames from Files

In [5]:
import pandas as pd
coffee = pd.read_csv('./coffee.CSV')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [64]:
results = pd.read_parquet('./results.parquet')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None